### ISSUE TITLE
Detect SiteOrigin Premium, and use its menu group instead of creating one

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-installer#1]
When both the [SiteOrgin Installer](https://github.com/siteorigin/siteorigin-installer) and SiteOrigin Premium are installed, there are two menu groups visible called SiteOrigin. The SiteOrigin Installer should be merged with the (better) premium menu group.

![](https://i.imgur.com/OSa0mk6.png)

**Comment by gregpriday** [comment]
Turns out this was already fixed in develop. The issue was only in master. I've pushed an update though.
